language: csharp
solution: Re-Usable Resources.sln
install:
  - nuget restore Re-Usable Resources.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
 - msbuild /p:Configuration=Release Re-Usable Resources.sln