name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Restoring nuget packages...
      run: dotnet restore
    - name: Build Solution.
      run: dotnet build --framework netstandard2.0
    - name: Running Test Cases...
      run: dotnet test
